name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--shamefully-hoist, --strict-peer-dependencies=false]

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint --fix

      - name: Check
        run: pnpm astro check


  cSpell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cSpell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          incremental_files_only: true
          config: .cspell.json
          files: |
            **/*.js
            **/*.ts
            **/*.astro
